export { rootVarManager } from './Utils'
export type { ITheme } from './Style/Interfaces'
export { default as theme } from './Style/theme'
export { FolderClass, FileClass, HierarchicalElement } from './Entities'
export type { tabStatusEnum } from './Entities'
export { TabProbider, useTab, ExplorerProvider, useExplorer } from './Context'
export type { IChildren } from './Utils/interfaces'
